version: '3'
services:
  nexus:
    image: klo2k/nexus3
    container_name: nexus
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
    restart: always
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: always

  zatca-spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zatca-spring-api
    ports:
      - 8082:8082
      - 9092:9092
    restart: always

volumes:
  nexus-data:
  jenkins-data:
