version: '3'
services:
  # nexus:
  #   image: klo2k/nexus3
  #   container_name: nexus
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - nexus-data:/var/nexus-data
  #   restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  zatca-spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zatca-spring-api
    ports:
      - 8082:8082
      - 9092:9092
    environment:
      - DATABASE_SERVER=jdbc:postgresql://postgres-db:5432/invoicedb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres-db
    restart: always

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=invoicedb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  jenkins-data:
  postgres-data:
