version: '3'
services:
  nexus:
    image: klo2k/nexus3
    container_name: nexus
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/var/nexus-data
    restart: always
  # nexus:
  #   image: sonatype/nexus3
  #   container_name: nexus
  #   ports:
  #     - 8081:8081
  #   volumes:
  #     - nexus-data:/nexus-data
  #   restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # Volume mount for Docker socket
    restart: always
    command: >-
      sh -c "chown -R jenkins:jenkins /var/jenkins_home &&
      chmod 664 /var/run/docker.sock &&
      su -c '/sbin/tini -- /usr/local/bin/jenkins.sh' jenkins"

  zatca-spring-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zatca-spring-api
    ports:
      - 8082:8082
      - 9092:9092
    restart: always

volumes:
  nexus-data:
  jenkins-data:
